### ISSUE TITLE
ServiceWorker does not working

### ISSUE THREAD

**Issue by Ariex** [kenchris/crosswalk-kitchensink#4]
I have compiler your code with crosswalk as below

```
python make_apk.py --package=org.crosswalkproject.example --manifest=X:/path/to/manifest.json --app-versionCode=1 --enable-remote-debugging
```

then when running in a emulator. I get an error: "`Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.`".

I have tried use crosswalk web-view with phonegap, and ends up with same error..

Can you help me with this?

Thank you~

**Comment by boender** [comment]
I have the same problem because the origin needs 2be served from HTTPS or Localhost

**Comment by Ariex** [comment]
thanks for your reply~
